
COLOR=1

COLOR_ESCAPE=\033[
COLOR_END=m

ifeq ($(COLOR),1)
COLOR_BLACK=$(COLOR_ESCAPE)30$(COLOR_END)
COLOR_RED=$(COLOR_ESCAPE)31$(COLOR_END)
COLOR_GREEN=$(COLOR_ESCAPE)32$(COLOR_END)
COLOR_ORANGE=$(COLOR_ESCAPE)33$(COLOR_END)
COLOR_BLUE=$(COLOR_ESCAPE)34$(COLOR_END)
COLOR_PURPLE=$(COLOR_ESCAPE)35$(COLOR_END)
COLOR_CYAN=$(COLOR_ESCAPE)36$(COLOR_END)
COLOR_GREY=$(COLOR_ESCAPE)37$(COLOR_END)

COLOR_DARK_GREY=$(COLOR_ESCAPE)90$(COLOR_END)
COLOR_LIGHT_RED=$(COLOR_ESCAPE)91$(COLOR_END)
COLOR_LIGHT_GREEN=$(COLOR_ESCAPE)92$(COLOR_END)
COLOR_YELLOW=$(COLOR_ESCAPE)93$(COLOR_END)
COLOR_LIGHT_BLUE=$(COLOR_ESCAPE)94$(COLOR_END)
COLOR_TURQUOISE=$(COLOR_ESCAPE)95$(COLOR_END)
COLOR_LIGHT_CYAN=$(COLOR_ESCAPE)96$(COLOR_END)
COLOR_WHITE=$(COLOR_ESCAPE)97$(COLOR_END)

COLOR_BLACK_BACKGROUND=$(COLOR_ESCAPE)40$(COLOR_END)
COLOR_RED_BACKGROUND=$(COLOR_ESCAPE)41$(COLOR_END)
COLOR_GREEN_BACKGROUND=$(COLOR_ESCAPE)42$(COLOR_END)
COLOR_ORANGE_BACKGROUND=$(COLOR_ESCAPE)43$(COLOR_END)
COLOR_BLUE_BACKGROUND=$(COLOR_ESCAPE)44$(COLOR_END)
COLOR_PURPLE_BACKGROUND=$(COLOR_ESCAPE)45$(COLOR_END)
COLOR_CYAN_BACKGROUND=$(COLOR_ESCAPE)46$(COLOR_END)
COLOR_GREY_BACKGROUND=$(COLOR_ESCAPE)47$(COLOR_END)

COLOR_DARK_GREY_BACKGROUND=$(COLOR_ESCAPE)100$(COLOR_END)
COLOR_LIGHT_RED_BACKGROUND=$(COLOR_ESCAPE)101$(COLOR_END)
COLOR_LIGHT_GREEN_BACKGROUND=$(COLOR_ESCAPE)102$(COLOR_END)
COLOR_YELLOW_BACKGROUND=$(COLOR_ESCAPE)103$(COLOR_END)
COLOR_LIGHT_BLUE_BACKGROUND=$(COLOR_ESCAPE)104$(COLOR_END)
COLOR_TURQUOISE_BACKGROUND=$(COLOR_ESCAPE)105$(COLOR_END)
COLOR_LIGHT_CYAN_BACKGROUND=$(COLOR_ESCAPE)106$(COLOR_END)
COLOR_WHITE_BACKGROUND=$(COLOR_ESCAPE)107$(COLOR_END)

COLOR_RESET=$(COLOR_ESCAPE)0$(COLOR_END)
COLOR_BOLD=$(COLOR_ESCAPE)1$(COLOR_END)
COLOR_UNDERLINE=$(COLOR_ESCAPE)4$(COLOR_END)
COLOR_FLASH=$(COLOR_ESCAPE)5$(COLOR_END)
COLOR_REVERSE=$(COLOR_ESCAPE)7$(COLOR_END)
COLOR_INVISIBLE=$(COLOR_ESCAPE)8$(COLOR_END)
else
COLOR_BLACK=
COLOR_RED=
COLOR_GREEN=
COLOR_ORANGE=
COLOR_BLUE=
COLOR_PURPLE=
COLOR_CYAN=
COLOR_GREY=

COLOR_DARK_GREY=
COLOR_LIGHT_RED=
COLOR_LIGHT_GREEN=
COLOR_YELLOW=
COLOR_LIGHT_BLUE=
COLOR_TURQUOISE=
COLOR_LIGHT_CYAN=
COLOR_WHITE=

COLOR_BLACK_BACKGROUND=
COLOR_RED_BACKGROUND=
COLOR_GREEN_BACKGROUND=
COLOR_ORANGE_BACKGROUND=
COLOR_BLUE_BACKGROUND=
COLOR_PURPLE_BACKGROUND=
COLOR_CYAN_BACKGROUND=
COLOR_GREY_BACKGROUND=

COLOR_DARK_GREY_BACKGROUND=
COLOR_LIGHT_RED_BACKGROUND=
COLOR_LIGHT_GREEN_BACKGROUND=
COLOR_YELLOW_BACKGROUND=
COLOR_LIGHT_BLUE_BACKGROUND=
COLOR_TURQUOISE_BACKGROUND=
COLOR_LIGHT_CYAN_BACKGROUND=
COLOR_WHITE_BACKGROUND=

COLOR_RESET=
COLOR_BOLD=
COLOR_UNDERLINE=
COLOR_FLASH=
COLOR_REVERSE=
COLOR_INVISIBLE=
endif
