-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(viewer)
TARGET=$(BIN_DIRECTORY)viewer
-include $(ROOT_PROJECT_DIRECTORY)src/executable.mk
