-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(matcher_builder)
TARGET=$(BIN_DIRECTORY)matcher-builder
-include $(ROOT_PROJECT_DIRECTORY)src/executable.mk
